### ISSUE TITLE
How to multithread/speed up city mode

### ISSUE THREAD

**Issue by JulesL2** [ThomasParistech/pretty-gpx#15]
This issue is created to discuss about the solutions to speed up the city mode.

I have tried multithreading and it does not seem to improve anything as we are limited by the overpy requests and on the Overpass forum, I have found a topic saying that it is 1 request per IP at the same time on official instance,

> Note that there's a limit of one request per IP at the same time on the official instance. That most likely doesn't apply if you're running your own instance, unless you set it up explicitly. (see [https://help.openstreetmap.org/questions/49754/does-overpass-handle-requests-sequentially](url))

Diving a bit more in the data collection and will try to see how we can manage to speed up the data handling (multiple output on the same query for example)

**Comment by ThomasParistech** [comment]
It's definitely worth having a look indeed !

**Comment by JulesL2** [comment]
Using an unique custom requests containing all request, without multithreading, I am able to get all roads in 15s (vs 50s before)
The process of the unique query e.g. splitting the result and then load them in an overpy.Result class could be multithreaded which could save a couple of seconds 

I will open a PR to refactor the code to allow multiple overpass queries in a single request

**Comment by JulesL2** [comment]
however, the total data downloaded for paris marathon is about 100Mo and I have a gigabit connection, the results will be impacted with slower internet connections

**Comment by ThomasParistech** [comment]
The 100Mo contains the roads, rivers and parks ? because on my side the roads file for the paris marathon is about 10Mo

**Comment by ThomasParistech** [comment]
We're probably not the firsts trying to efficiently query the roads of a given latitude/longitude bbox. We could benchmark other existing solutions and get inspired from them, if some of them are any faster.

The devil is in the details

- osmnx: slower because it builds the whole connected graph, but the request part might be interesting. https://github.com/gboeing/osmnx
- OsmGT: haven't tested yet, but looks similar to us. https://github.com/amauryval/OsmGT/blob/master/osmgt/helpers/global_values.py#L46
- ...

**Comment by JulesL2** [comment]
Yes, I have also seen that we should get response without metadata using 
`out skel` or `out skel geom`.

**Comment by JulesL2** [comment]
Using ujson package instead of json package allows also a performance improvement as we deal with large JSON files (more than 100k entries sometimes more than 1M)

**Comment by JulesL2** [comment]
In order of magnitude, with the PR https://github.com/ThomasParistech/pretty-gpx/pull/19 we spend 10s to create and download the data and 5s to process it. The only time we can reduce is the 5s to process it as we can probably add multithreading.

**Comment by JulesL2** [comment]
See PR https://github.com/ThomasParistech/pretty-gpx/pull/19 comments to see the improvements with the profiling.

80% of the time is download, 20% of the time is loading data into the overpy package. 
With multithreading we can reduce the time of the loading phase which is now only 20% 

This issue can be reopened if the time taken to fetch overpass data is a problem in some use cases
