### ISSUE TITLE
Add the python3 minimum version requirement

### ISSUE THREAD

**Issue by JulesL2** [ThomasParistech/pretty-gpx#4]
Hi,
You should add that your code works only with python >= 3.10 as you use the `|` operand in drawing_data.py for example `float | list[float]`

You can add a setup.cfg with python_requires argument but I do not know where you prefer to add it root or .devcontainer ?

Thank you for the code

**Comment by ThomasParistech** [comment]
Good point! I'll have a look

**Comment by ThomasParistech** [comment]
See commit https://github.com/ThomasParistech/pretty-gpx/commit/e948970c87c89a56bf03fba3bdfb825ac7d4477f

**Comment by ThomasParistech** [comment]
See commit https://github.com/ThomasParistech/pretty-gpx/commit/e948970c87c89a56bf03fba3bdfb825ac7d4477f
